//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SssIndex {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class SssIndexSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static SssIndexSettings defaultInstance = ((SssIndexSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SssIndexSettings())));
        
        public static SssIndexSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>QQn.SourceServerIndexer.Providers.SubversionResolver, QQn.SourceServerIndexer</string>
  <string>QQn.SourceServerIndexer.Providers.TeamFoundationResolver, QQn.SourceServerIndexer</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Resolvers {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Resolvers"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%programfiles%\\Debugging Tools for Windows\\sdk\\srcsrv")]
        public string DebuggingSdkDir {
            get {
                return ((string)(this["DebuggingSdkDir"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>autodetect</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection UseResolvers {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["UseResolvers"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>%programfiles%\\Subversion\\bin</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection AppendToPath {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AppendToPath"]));
            }
        }
    }
}
